const provincesPrices = [
    { id: 1, name: { en: "Adrar", ar: "أدرار" }, price: 500 },
    { id: 2, name: { en: "Chlef", ar: " الشلف" }, price: 500 },
    { id: 3, name: { en: "Laghouat", ar: "الأغواط" }, price: 500 },
    { id: 4, name: { en: "Oum El Bouaghi", ar: "أم البواقي" }, price: 500 },
    { id: 5, name: { en: "Batna", ar: "باتنة" }, price: 500 },
    { id: 6, name: { en: "Béjaïa", ar: " بجاية" }, price: 500 },
    { id: 7, name: { en: "Biskra", ar: "بسكرة" }, price: 500 },
    { id: 8, name: { en: "Béchar", ar: "بشار" }, price: 500 },
    { id: 9, name: { en: "Blida", ar: "البليدة" }, price: 500 },
    { id: 10, name: { en: "Bouira", ar: "البويرة" }, price: 500 },
    { id: 11, name: { en: "Tamanrasset", ar: "تمنراست" }, price: 500 },
    { id: 12, name: { en: "Tébessa", ar: "تبسة" }, price: 500 },
    { id: 13, name: { en: "Tlemcen", ar: "تلمسان" }, price: 500 },
    { id: 14, name: { en: "Tiaret", ar: "تيارت" }, price: 500 },
    { id: 15, name: { en: "Tizi Ouzou", ar: "تيزي وزو" }, price: 500 },
    { id: 16, name: { en: "Alger", ar: "الجزائر" }, price: 500 },
    { id: 17, name: { en: "Djelfa", ar: "الجلفة" }, price: 1000 },
    { id: 18, name: { en: "Jijel", ar: "جيجل" }, price: 700 },
    { id: 19, name: { en: "Sétif", ar: "سطيف" }, price: 500 },
    { id: 20, name: { en: "Saïda", ar: "سعيدة" }, price: 500 },
    { id: 21, name: { en: "Skikda", ar: "سكيكدة" }, price: 500 },
    { id: 22, name: { en: "Sidi Bel Abbès", ar: "سيدي بلعباس" }, price: 500 },
    { id: 23, name: { en: "Annaba", ar: "عنابة" }, price: 500 },
    { id: 24, name: { en: "Guelma", ar: "قالمة" }, price: 500 },
    { id: 25, name: { en: "Constantine", ar: "قسنطينة" }, price: 500 },
    { id: 26, name: { en: "Médéa", ar: "المدية" }, price: 500 },
    { id: 27, name: { en: "Mostaganem", ar: "مستغانم" }, price: 500 },
    { id: 28, name: { en: "M'Sila", ar: "المسيلة" }, price: 500 },
    { id: 29, name: { en: "Mascara", ar: "معسكر" }, price: 500 },
    { id: 30, name: { en: "Ouargla", ar: "ورقلة" }, price: 500 },
    { id: 31, name: { en: "Oran", ar: "وهران" }, price: 500 },
    { id: 32, name: { en: "El Bayadh", ar: "البيض" }, price: 500 },
    { id: 33, name: { en: "Illizi", ar: "إليزي" }, price: 500 },
    {
        id: 34,
        name: { en: "Bordj Bou Arreridj", ar: "برج بوعريريج" },
        price: 500,
    },
    { id: 35, name: { en: "Boumerdès", ar: "بومرداس" }, price: 300 },
    { id: 36, name: { en: "El Tarf", ar: "الطارف" }, price: 500 },
    { id: 37, name: { en: "Tindouf", ar: "تندوف" }, price: 500 },
    { id: 38, name: { en: "Tissemsilt", ar: "تيسمسيلت" }, price: 500 },
    { id: 39, name: { en: "El Oued", ar: "الوادي" }, price: 500 },
    { id: 40, name: { en: "Khenchela", ar: "خنشلة" }, price: 500 },
    { id: 41, name: { en: "Souk Ahras", ar: "سوق أهراس" }, price: 500 },
    { id: 42, name: { en: "Tipaza", ar: "تيبازة" }, price: 500 },
    { id: 43, name: { en: "Mila", ar: "ميلة" }, price: 500 },
    { id: 44, name: { en: "Aïn Defla", ar: "عين الدفلة" }, price: 500 },
    { id: 45, name: { en: "Naâma", ar: "النعامة" }, price: 500 },
    { id: 46, name: { en: "Aïn Témouchent", ar: "عين تيموشنت" }, price: 500 },
    { id: 47, name: { en: "Ghardaïa", ar: "غرداية" }, price: 500 },
    { id: 48, name: { en: "Relizane", ar: "غليزان" }, price: 500 },
    { id: 49, name: { en: "Timimoun", ar: "تيميمون" }, price: 500 },
    {
        id: 50,
        name: { en: "Bordj Badji Mokhtar", ar: "برج باجي مختار" },
        price: 500,
    },
    { id: 51, name: { en: "Ouled Djellal", ar: "أولاد جلال" }, price: 500 },
    { id: 52, name: { en: "Béni Abbès", ar: "بني عباس" }, price: 500 },
    { id: 53, name: { en: "In Salah", ar: "عين صالح" }, price: 500 },
    { id: 54, name: { en: "In Guezzam", ar: "عين قزام" }, price: 500 },
    { id: 55, name: { en: "Touggourt", ar: "تقرت" }, price: 500 },
    { id: 56, name: { en: "Djanet", ar: "جانت" }, price: 500 },
    { id: 57, name: { en: "El Meghaier", ar: "المغير" }, price: 500 },
    { id: 58, name: { en: "El Menia", ar: "المنيعة" }, price: 500 },
];

export const provincesPricesMap = new Map(
    provincesPrices.map((province) => [province.id, province])
);
